import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Geist Sans 폰트 설정 - 본문 및 UI 요소용
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Geist Mono 폰트 설정 - 코드 블록 및 모노스페이스 텍스트용
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 페이지 메타데이터 - SEO 및 브라우저 탭 정보
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 루트 레이아웃 컴포넌트 - 모든 페이지를 감싸는 최상위 레이아웃
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
